<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLho5veo\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLho5veo/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLho5veo.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLho5veo\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLho5veo\appDevDebugProjectContainer([
    'container.build_hash' => 'Lho5veo',
    'container.build_id' => '197a74dc',
    'container.build_time' => 1556913508,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLho5veo');
