<?php

namespace FriendBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommentById($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT v FROM FriendBundle:Comment v where v.event = '$id' ");
        return $query->getResult();
    }

    public function CommentefindAll($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT COUNT(v) FROM FriendBundle:Comment v where v.event = $id"  );

        return $query->getResult();
    }
}
