<?php

namespace FriendBundle\Repository;
use Doctrine\ORM\NonUniqueResultException;
use FriendBundle\Entity\Event;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{


    public function myfindlieu($lieu){
        $query = $this->createQueryBuilder('v')
            ->where('v.lieu LIKE :key')
            ->setParameter('key' , '%'.$lieu.'%')->getQuery();

        return $query->getResult();
    }

    public function myfindAll($titre){
        $query = $this->createQueryBuilder('v')
            ->where('v.titre LIKE :key')
            ->setParameter('key' , '%'.$titre.'%')->getQuery();

        return $query->getResult();
    }


    public function findEventByid($id)
    {
        try {
            return $this->getEntityManager()
                ->createQuery(
                    "SELECT p
                FROM FriendBundle:Event
                p WHERE p.id =:id"
                )
                ->setParameter('id', $id)
                ->getOneOrNullResult();
        } catch (NonUniqueResultException $e) {
        }
    }

}
