<?php

namespace FriendBundle\Repository;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParticipant($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT q FROM FriendBundle:Participant q where q.event ='$id'");
        return $query->getResult();
    }
}
