<?php

namespace ActivityBundle\Repository;

/**
 * RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RatingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findrating($idact){
        $query=$this->getEntityManager()
            ->createQuery("select r from ActivityBundle:Rating r where r.idact='$idact'");
        return $query->getResult();
    }
}
